name: Deploy Helm chart to local K8s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/runner/.kube/config

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Helm upgrade/install
      run: |
        helm upgrade --install myapp ./myapp \
          --namespace default \
          --create-namespace
